import { Achievement } from '../types/playerTypes';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_victory',
    title: 'First Victory',
    description: 'Win your first game in Ludo Royale.',
    icon: '🏅',
    target: 1,
    progress: 0,
    unlocked: false,
    rewardCoins: 100,
    rewardXp: 200,
  },
  {
    id: 'first_capture',
    title: 'First Capture',
    description: 'Capture your first opponent token.',
    icon: '🎯',
    target: 1,
    progress: 0,
    unlocked: false,
    rewardCoins: 50,
    rewardXp: 100,
  },
  {
    id: 'destroyer',
    title: 'Destroyer',
    description: 'Capture 5 opponent tokens across all games.',
    icon: '🔥',
    target: 5,
    progress: 0,
    unlocked: false,
    rewardCoins: 200,
    rewardXp: 350,
  },
  {
    id: 'ludo_master',
    title: 'Ludo Master',
    description: 'Win 25 games of Ludo Royale.',
    icon: '👑',
    target: 25,
    progress: 0,
    unlocked: false,
    rewardCoins: 1000,
    rewardXp: 1500,
  },
  {
    id: 'lucky_six',
    title: 'Lucky Six',
    description: 'Roll a six 15 times in your matches.',
    icon: '⚡',
    target: 15,
    progress: 0,
    unlocked: false,
    rewardCoins: 150,
    rewardXp: 250,
  },
  {
    id: 'champion',
    title: 'Champion',
    description: 'Reach Player Level 10.',
    icon: '🏆',
    target: 10,
    progress: 1,
    unlocked: false,
    rewardCoins: 500,
    rewardXp: 800,
  },
  {
    id: 'speed_demon',
    title: 'Speed Demon',
    description: 'Guide 10 tokens all the way into the home center.',
    icon: '🚀',
    target: 10,
    progress: 0,
    unlocked: false,
    rewardCoins: 300,
    rewardXp: 400,
  },
];
